-- ============================================================
-- EduBridge AI — Complete Supabase Schema + Seed Data
-- Platform helping international students find US universities
-- and scholarships.
-- ============================================================

-- ============================================================
-- 1. SCHEMA
-- ============================================================

-- ---------- profiles ----------
CREATE TABLE profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  country TEXT DEFAULT '',
  date_of_birth DATE,
  gender TEXT,
  first_generation BOOLEAN DEFAULT false,
  low_income BOOLEAN DEFAULT false,
  gpa NUMERIC(4,2),
  gpa_scale TEXT DEFAULT '4.0',
  intended_major TEXT,
  education_level TEXT DEFAULT 'high_school',
  academic_strengths TEXT,
  extracurriculars TEXT[],
  sat_score INTEGER,
  act_score INTEGER,
  toefl_score INTEGER,
  ielts_score NUMERIC(2,1),
  english_level INTEGER,
  test_optional_preference BOOLEAN DEFAULT false,
  destination_country TEXT DEFAULT 'US',
  target_start_term TEXT,
  preferred_school_type TEXT,
  preferred_states TEXT[],
  preferred_campus_size TEXT,
  preferred_setting TEXT,
  annual_family_income TEXT,
  max_annual_budget INTEGER,
  needs_full_scholarship BOOLEAN DEFAULT false,
  willing_community_college_transfer BOOLEAN DEFAULT false,
  needs_f1_visa BOOLEAN DEFAULT true,
  plans_to_work BOOLEAN DEFAULT false,
  work_goals TEXT,
  support_needs TEXT[],
  onboarding_completed BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own profile"
  ON profiles FOR SELECT
  USING (auth.uid() = id);

CREATE POLICY "Users can insert own profile"
  ON profiles FOR INSERT
  WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile"
  ON profiles FOR UPDATE
  USING (auth.uid() = id);

-- Trigger: auto-create profile on signup
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO profiles (id, full_name, email)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', ''),
    COALESCE(NEW.email, '')
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ---------- universities ----------
CREATE TABLE universities (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  city TEXT NOT NULL,
  state TEXT NOT NULL,
  type TEXT NOT NULL,
  acceptance_rate NUMERIC(5,2),
  avg_sat INTEGER,
  avg_act INTEGER,
  min_toefl INTEGER,
  min_ielts NUMERIC(2,1),
  tuition_in_state INTEGER,
  tuition_out_of_state INTEGER,
  tuition_international INTEGER,
  room_and_board INTEGER,
  estimated_total_cost INTEGER,
  avg_financial_aid INTEGER,
  international_aid_available BOOLEAN DEFAULT false,
  merit_scholarships_available BOOLEAN DEFAULT false,
  need_blind_international BOOLEAN DEFAULT false,
  test_optional BOOLEAN DEFAULT false,
  total_enrollment INTEGER,
  international_student_pct NUMERIC(4,1),
  student_faculty_ratio TEXT,
  popular_majors TEXT[],
  campus_setting TEXT,
  website TEXT,
  description TEXT,
  image_url TEXT,
  us_news_rank INTEGER,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_universities_state ON universities(state);
CREATE INDEX idx_universities_type ON universities(type);
CREATE INDEX idx_universities_acceptance_rate ON universities(acceptance_rate);
CREATE INDEX idx_universities_tuition_international ON universities(tuition_international);

ALTER TABLE universities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Universities are publicly readable"
  ON universities FOR SELECT
  USING (true);

-- ---------- scholarships ----------
CREATE TABLE scholarships (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  provider TEXT NOT NULL,
  type TEXT NOT NULL,
  amount_min INTEGER,
  amount_max INTEGER,
  covers_tuition BOOLEAN DEFAULT false,
  covers_living BOOLEAN DEFAULT false,
  renewable BOOLEAN DEFAULT false,
  duration_years INTEGER DEFAULT 1,
  eligible_countries TEXT[],
  eligible_majors TEXT[],
  min_gpa NUMERIC(3,2),
  min_toefl INTEGER,
  min_ielts NUMERIC(2,1),
  education_level TEXT[],
  income_requirement TEXT,
  first_gen_only BOOLEAN DEFAULT false,
  deadline TEXT,
  application_url TEXT,
  description TEXT,
  requirements TEXT,
  university_id INTEGER REFERENCES universities(id),
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_scholarships_type ON scholarships(type);
CREATE INDEX idx_scholarships_university_id ON scholarships(university_id);
CREATE INDEX idx_scholarships_min_gpa ON scholarships(min_gpa);

ALTER TABLE scholarships ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Scholarships are publicly readable"
  ON scholarships FOR SELECT
  USING (true);

-- ---------- saved_matches ----------
CREATE TABLE saved_matches (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  university_id INTEGER REFERENCES universities(id),
  scholarship_id INTEGER REFERENCES scholarships(id),
  match_score INTEGER,
  match_reasons TEXT[],
  estimated_net_cost INTEGER,
  difficulty_level TEXT,
  status TEXT DEFAULT 'recommended',
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_saved_matches_user_id ON saved_matches(user_id);

ALTER TABLE saved_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own matches"
  ON saved_matches FOR ALL
  USING (auth.uid() = user_id);

-- ---------- chat_messages ----------
CREATE TABLE chat_messages (
  id SERIAL PRIMARY KEY,
  user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_chat_messages_user_created ON chat_messages(user_id, created_at);

ALTER TABLE chat_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can manage own chat messages"
  ON chat_messages FOR ALL
  USING (auth.uid() = user_id);


-- ============================================================
-- 2. SEED DATA — UNIVERSITIES
-- ============================================================

-- ---- TIER 1: Highly Selective (15) ----

INSERT INTO universities (name, slug, city, state, type, acceptance_rate, avg_sat, avg_act, min_toefl, min_ielts, tuition_in_state, tuition_out_of_state, tuition_international, room_and_board, estimated_total_cost, avg_financial_aid, international_aid_available, merit_scholarships_available, need_blind_international, test_optional, total_enrollment, international_student_pct, student_faculty_ratio, popular_majors, campus_setting, website, description, us_news_rank) VALUES
('Harvard University', 'harvard', 'Cambridge', 'MA', 'private_nonprofit', 3.41, 1520, 34, 100, 7.0, 56550, 56550, 56550, 21130, 77680, 55000, true, false, true, true, 22947, 13.0, '6:1', ARRAY['Economics','Computer Science','Political Science','Mathematics','Biology'], 'urban', 'https://www.harvard.edu', 'Harvard meets 100% of demonstrated financial need for all admitted students including international students. About 55% of students receive need-based scholarships. The average grant covers most of tuition and fees.', 3),
('Massachusetts Institute of Technology', 'mit', 'Cambridge', 'MA', 'private_nonprofit', 3.96, 1540, 35, 100, 7.0, 57986, 57986, 57986, 19680, 77666, 53000, true, false, true, true, 11520, 11.3, '3:1', ARRAY['Computer Science','Engineering','Mathematics','Physics','Biology'], 'urban', 'https://www.mit.edu', 'MIT is need-blind for international students and meets 100% of demonstrated financial need. Over 60% of undergraduates receive MIT scholarships. Strong support for international STEM students.', 2),
('Stanford University', 'stanford', 'Stanford', 'CA', 'private_nonprofit', 3.68, 1530, 34, 100, 7.0, 56169, 56169, 56169, 19134, 75303, 56000, true, false, true, true, 17534, 12.8, '5:1', ARRAY['Computer Science','Engineering','Biology','Economics','Psychology'], 'suburban', 'https://www.stanford.edu', 'Stanford meets 100% of demonstrated financial need for admitted students. Families with income below $75k pay no tuition, room, or board. Generous financial aid extends to international students.', 4),
('Princeton University', 'princeton', 'Princeton', 'NJ', 'private_nonprofit', 3.73, 1530, 34, 100, 7.0, 57410, 57410, 57410, 19380, 76790, 58000, true, false, true, true, 8478, 12.5, '4:1', ARRAY['Computer Science','Economics','Public Policy','Engineering','History'], 'suburban', 'https://www.princeton.edu', 'Princeton provides grant-based financial aid with no loans. The university meets 100% of demonstrated need for all students including internationals. Over 60% of students receive financial aid.', 1),
('Yale University', 'yale', 'New Haven', 'CT', 'private_nonprofit', 4.35, 1530, 34, 100, 7.0, 62250, 62250, 62250, 18450, 80700, 56000, true, false, true, true, 14776, 12.3, '6:1', ARRAY['Economics','Political Science','History','Biology','Computer Science'], 'urban', 'https://www.yale.edu', 'Yale is need-blind for international students and meets 100% of demonstrated need. Strong liberal arts focus with world-class resources. Over 65% of students receive financial aid.', 5),
('California Institute of Technology', 'caltech', 'Pasadena', 'CA', 'private_nonprofit', 2.67, 1560, 36, 100, 7.0, 60864, 60864, 60864, 19539, 80403, 50000, true, false, false, false, 2397, 9.1, '3:1', ARRAY['Physics','Computer Science','Engineering','Mathematics','Chemistry'], 'suburban', 'https://www.caltech.edu', 'Caltech is one of the most selective STEM-focused universities in the world. Small class sizes provide unmatched research opportunities. Financial aid is available for international students based on need.', 6),
('Columbia University', 'columbia', 'New York', 'NY', 'private_nonprofit', 3.85, 1530, 34, 100, 7.0, 65524, 65524, 65524, 16800, 82324, 55000, true, false, true, true, 33413, 18.1, '6:1', ARRAY['Computer Science','Economics','Political Science','Biology','Psychology'], 'urban', 'https://www.columbia.edu', 'Located in New York City, Columbia offers unparalleled access to internships and cultural experiences. Need-blind for international students with 100% need met. Strong Core Curriculum.', 12),
('University of Pennsylvania', 'upenn', 'Philadelphia', 'PA', 'private_nonprofit', 5.37, 1520, 34, 100, 7.0, 63452, 63452, 63452, 18200, 81652, 52000, true, true, true, true, 22432, 14.2, '6:1', ARRAY['Finance','Nursing','Computer Science','Economics','Biology'], 'urban', 'https://www.upenn.edu', 'Penn is need-blind for international students and meets 100% of demonstrated need. The Wharton School is world-renowned for business. Strong interdisciplinary programs.', 6),
('Duke University', 'duke', 'Durham', 'NC', 'private_nonprofit', 5.02, 1520, 34, 100, 7.0, 63054, 63054, 63054, 18692, 81746, 53000, true, true, false, true, 17620, 12.5, '6:1', ARRAY['Computer Science','Public Policy','Biology','Economics','Engineering'], 'suburban', 'https://www.duke.edu', 'Duke provides generous financial aid to international students. Known for strong pre-med, engineering, and public policy programs. Beautiful campus in Research Triangle area.', 7),
('Johns Hopkins University', 'johns-hopkins', 'Baltimore', 'MD', 'private_nonprofit', 6.48, 1520, 34, 100, 7.0, 60480, 60480, 60480, 18200, 78680, 45000, true, true, false, true, 27651, 13.5, '7:1', ARRAY['Biomedical Engineering','Public Health','Neuroscience','Computer Science','Biology'], 'urban', 'https://www.jhu.edu', 'Johns Hopkins is the top research university in the US by R&D spending. Exceptional pre-med and biomedical engineering programs. International students can receive need-based aid.', 9),
('Northwestern University', 'northwestern', 'Evanston', 'IL', 'private_nonprofit', 5.62, 1520, 34, 100, 7.0, 62391, 62391, 62391, 19413, 81804, 49000, true, true, false, true, 22601, 10.8, '6:1', ARRAY['Economics','Journalism','Engineering','Computer Science','Psychology'], 'suburban', 'https://www.northwestern.edu', 'Northwestern combines strong academics with top journalism and performing arts programs. Near Chicago for internship opportunities. Merit and need-based aid for internationals.', 9),
('Brown University', 'brown', 'Providence', 'RI', 'private_nonprofit', 5.08, 1520, 34, 100, 7.0, 65146, 65146, 65146, 17526, 82672, 52000, true, false, false, true, 10696, 14.1, '6:1', ARRAY['Computer Science','Economics','Biology','Applied Mathematics','Engineering'], 'urban', 'https://www.brown.edu', 'Brown offers an open curriculum with no required courses outside the major. Strong support for international students. Need-based financial aid available for internationals.', 9),
('Dartmouth College', 'dartmouth', 'Hanover', 'NH', 'private_nonprofit', 6.24, 1520, 34, 100, 7.0, 62430, 62430, 62430, 18045, 80475, 55000, true, true, true, true, 6795, 9.5, '7:1', ARRAY['Economics','Government','Computer Science','Engineering','Biology'], 'rural', 'https://www.dartmouth.edu', 'Dartmouth is need-blind for international students and meets 100% of demonstrated need. Intimate liberal arts experience with Ivy League resources. Strong D-Plan allows flexible scheduling.', 13),
('University of Chicago', 'uchicago', 'Chicago', 'IL', 'private_nonprofit', 5.18, 1540, 35, 100, 7.0, 62940, 62940, 62940, 19152, 82092, 47000, true, true, false, true, 17834, 16.2, '5:1', ARRAY['Economics','Mathematics','Computer Science','Biology','Political Science'], 'urban', 'https://www.uchicago.edu', 'UChicago is known for intellectual rigor and its famous Core Curriculum. Strong economics and mathematics programs. International students receive need-based and merit aid.', 12),
('Rice University', 'rice', 'Houston', 'TX', 'private_nonprofit', 7.68, 1530, 35, 100, 7.0, 54960, 54960, 54960, 16250, 71210, 48000, true, true, false, true, 8285, 15.8, '6:1', ARRAY['Computer Science','Engineering','Biology','Economics','Architecture'], 'urban', 'https://www.rice.edu', 'Rice offers exceptional value among elite universities with lower tuition. Strong engineering and sciences. Residential college system fosters tight-knit community. Generous aid for internationals.', 14);

-- ---- TIER 2: Selective Private (20) ----

INSERT INTO universities (name, slug, city, state, type, acceptance_rate, avg_sat, avg_act, min_toefl, min_ielts, tuition_in_state, tuition_out_of_state, tuition_international, room_and_board, estimated_total_cost, avg_financial_aid, international_aid_available, merit_scholarships_available, need_blind_international, test_optional, total_enrollment, international_student_pct, student_faculty_ratio, popular_majors, campus_setting, website, description, us_news_rank) VALUES
('Boston University', 'boston-university', 'Boston', 'MA', 'private_nonprofit', 11.38, 1460, 33, 90, 7.0, 62360, 62360, 62360, 18390, 80750, 42000, true, true, false, true, 36714, 24.1, '10:1', ARRAY['Business','Engineering','Biology','Communication','Computer Science'], 'urban', 'https://www.bu.edu', 'BU offers Trustee, Presidential, and Dean scholarships for international students covering partial to full tuition. Located in the heart of Boston with co-op and internship programs.', 41),
('New York University', 'nyu', 'New York', 'NY', 'private_nonprofit', 12.18, 1480, 33, 100, 7.5, 58168, 58168, 58168, 20780, 78948, 38000, true, true, false, true, 58226, 22.4, '9:1', ARRAY['Business','Film','Liberal Studies','Computer Science','Economics'], 'urban', 'https://www.nyu.edu', 'NYU has one of the largest international student populations in the US. Global campuses in Abu Dhabi and Shanghai offer full scholarships. Wagner, Stern, and Tisch are world-renowned.', 35),
('University of Southern California', 'usc', 'Los Angeles', 'CA', 'private_nonprofit', 9.20, 1490, 34, 100, 7.0, 63468, 63468, 63468, 18444, 81912, 40000, true, true, false, true, 47310, 16.3, '9:1', ARRAY['Business','Film','Engineering','Computer Science','Communication'], 'urban', 'https://www.usc.edu', 'USC enrolls more international students than almost any private US university. Strong film, engineering, and business programs. Located in Los Angeles with industry connections.', 28),
('Tulane University', 'tulane', 'New Orleans', 'LA', 'private_nonprofit', 11.00, 1440, 32, 90, 6.5, 60814, 60814, 60814, 17110, 77924, 38000, true, true, false, true, 13637, 7.8, '8:1', ARRAY['Business','Public Health','Biology','Political Science','Psychology'], 'urban', 'https://www.tulane.edu', 'Tulane offers merit scholarships to international students. Unique community service graduation requirement. Strong public health and business programs in vibrant New Orleans.', 42),
('Emory University', 'emory', 'Atlanta', 'GA', 'private_nonprofit', 11.43, 1490, 33, 100, 7.0, 57948, 57948, 57948, 17400, 75348, 42000, true, true, false, true, 15252, 18.8, '9:1', ARRAY['Business','Biology','Nursing','Computer Science','Psychology'], 'suburban', 'https://www.emory.edu', 'Emory provides need-based financial aid to international students. Located near CDC headquarters making it ideal for public health. Strong pre-med and business programs.', 24),
('Georgetown University', 'georgetown', 'Washington', 'DC', 'private_nonprofit', 12.05, 1480, 33, 100, 7.0, 62052, 62052, 62052, 18636, 80688, 42000, true, true, false, true, 19771, 14.2, '11:1', ARRAY['International Relations','Government','Business','Biology','Computer Science'], 'urban', 'https://www.georgetown.edu', 'Georgetown is the top school for international relations and diplomacy. Located in Washington DC near embassies and international organizations. Diverse student body.', 22),
('Vanderbilt University', 'vanderbilt', 'Nashville', 'TN', 'private_nonprofit', 5.62, 1520, 34, 100, 7.0, 60348, 60348, 60348, 19352, 79700, 51000, true, true, false, true, 13710, 9.5, '7:1', ARRAY['Economics','Engineering','Computer Science','Education','Medicine'], 'urban', 'https://www.vanderbilt.edu', 'Vanderbilt offers the Cornelius Vanderbilt and Chancellor scholarships. Meets 100% of demonstrated need. Nashville provides a growing job market and cultural scene.', 18),
('Wake Forest University', 'wake-forest', 'Winston-Salem', 'NC', 'private_nonprofit', 21.28, 1430, 32, 100, 7.0, 59770, 59770, 59770, 17430, 77200, 38000, true, true, false, true, 8956, 8.7, '10:1', ARRAY['Business','Biology','Communication','Psychology','Economics'], 'suburban', 'https://www.wfu.edu', 'Wake Forest has a test-optional policy and strong mentorship culture. Merit scholarships available for international students. Small classes with personal attention.', 29),
('Tufts University', 'tufts', 'Medford', 'MA', 'private_nonprofit', 9.71, 1500, 34, 100, 7.0, 63000, 63000, 63000, 17400, 80400, 45000, true, true, false, true, 12594, 15.2, '9:1', ARRAY['International Relations','Computer Science','Biology','Economics','Engineering'], 'suburban', 'https://www.tufts.edu', 'Tufts is known for its global perspective and international relations program. Near Boston with access to city resources. Need-based aid available for international students.', 32),
('Brandeis University', 'brandeis', 'Waltham', 'MA', 'private_nonprofit', 31.36, 1420, 32, 90, 7.0, 60391, 60391, 60391, 17002, 77393, 38000, true, true, false, true, 5854, 21.3, '10:1', ARRAY['Biology','Economics','Business','Computer Science','Psychology'], 'suburban', 'https://www.brandeis.edu', 'Brandeis offers the Wien International Scholarship covering full tuition for exceptional international students. Research university with a liberal arts focus near Boston.', 60),
('Case Western Reserve University', 'case-western', 'Cleveland', 'OH', 'private_nonprofit', 27.58, 1440, 33, 90, 7.0, 54020, 54020, 54020, 17060, 71080, 40000, true, true, false, true, 12091, 22.6, '11:1', ARRAY['Engineering','Biology','Computer Science','Nursing','Business'], 'urban', 'https://www.case.edu', 'Case Western offers generous merit scholarships for international students up to full tuition. Strong engineering, nursing, and pre-med programs. Located near Cleveland Clinic.', 45),
('University of Rochester', 'rochester', 'Rochester', 'NY', 'private_nonprofit', 37.44, 1420, 33, 100, 7.0, 60550, 60550, 60550, 18128, 78678, 40000, true, true, false, true, 12179, 28.4, '10:1', ARRAY['Engineering','Biology','Music','Computer Science','Business'], 'suburban', 'https://www.rochester.edu', 'Rochester has a high percentage of international students and offers merit aid. Flexible curriculum lets students explore interests. Strong music program (Eastman School of Music).', 47),
('Rensselaer Polytechnic Institute', 'rpi', 'Troy', 'NY', 'private_nonprofit', 57.00, 1420, 32, 88, 7.0, 58526, 58526, 58526, 17370, 75896, 35000, true, true, false, false, 7442, 16.2, '13:1', ARRAY['Computer Science','Engineering','Business','Biology','Architecture'], 'suburban', 'https://www.rpi.edu', 'RPI is one of the oldest technological universities in the US. Merit scholarships available for international students. Strong engineering and CS programs with research focus.', 55),
('Lehigh University', 'lehigh', 'Bethlehem', 'PA', 'private_nonprofit', 32.06, 1400, 32, 90, 7.0, 58350, 58350, 58350, 16460, 74810, 38000, true, true, false, true, 7509, 11.5, '10:1', ARRAY['Engineering','Business','Biology','Computer Science','Finance'], 'suburban', 'https://www.lehigh.edu', 'Lehigh offers merit-based scholarships up to full tuition for international students. Strong engineering and business programs. Beautiful Lehigh Valley campus.', 51),
('Northeastern University', 'northeastern', 'Boston', 'MA', 'private_nonprofit', 5.56, 1510, 34, 99, 7.0, 60192, 60192, 60192, 19340, 79532, 32000, true, true, false, true, 22207, 22.6, '15:1', ARRAY['Computer Science','Engineering','Business','Health Sciences','Biology'], 'urban', 'https://www.northeastern.edu', 'Northeastern is famous for its co-op program giving students paid work experience. High international enrollment. Located in Boston with strong industry connections.', 40),
('Southern Methodist University', 'smu', 'Dallas', 'TX', 'private_nonprofit', 47.16, 1390, 31, 80, 6.5, 58540, 58540, 58540, 18750, 77290, 35000, true, true, false, true, 12322, 11.2, '11:1', ARRAY['Business','Engineering','Economics','Computer Science','Communication'], 'urban', 'https://www.smu.edu', 'SMU offers merit scholarships for international students. Located in Dallas with strong business and engineering programs. Beautiful campus with warm climate.', 67),
('American University', 'american-university', 'Washington', 'DC', 'private_nonprofit', 41.93, 1340, 31, 80, 6.5, 53868, 53868, 53868, 17340, 71208, 30000, true, true, false, true, 14575, 15.1, '12:1', ARRAY['International Relations','Political Science','Business','Communication','Economics'], 'urban', 'https://www.american.edu', 'American University in DC is ideal for students interested in government and international affairs. Emerging Global Leader scholarship covers full costs for one international student per year.', 72),
('George Washington University', 'gwu', 'Washington', 'DC', 'private_nonprofit', 41.80, 1390, 31, 90, 7.0, 60260, 60260, 60260, 15420, 75680, 36000, true, true, false, true, 26212, 12.5, '13:1', ARRAY['International Relations','Political Science','Business','Engineering','Biology'], 'urban', 'https://www.gwu.edu', 'GWU is located blocks from the White House offering unparalleled access to DC institutions. International merit scholarships available. Strong political science and international affairs.', 62),
('Santa Clara University', 'santa-clara', 'Santa Clara', 'CA', 'private_nonprofit', 42.88, 1380, 31, 90, 7.0, 56064, 56064, 56064, 17520, 73584, 32000, true, true, false, true, 9015, 9.3, '11:1', ARRAY['Computer Science','Engineering','Business','Biology','Finance'], 'urban', 'https://www.scu.edu', 'Santa Clara is located in the heart of Silicon Valley. Strong connections to tech companies for internships. Merit scholarships available for international students.', 60),
('Villanova University', 'villanova', 'Villanova', 'PA', 'private_nonprofit', 23.07, 1430, 33, 90, 7.0, 58492, 58492, 58492, 16460, 74952, 35000, true, true, false, true, 10684, 5.8, '12:1', ARRAY['Business','Engineering','Biology','Nursing','Computer Science'], 'suburban', 'https://www.villanova.edu', 'Villanova offers Presidential Scholarships for international students. Strong business school and engineering programs. Close to Philadelphia with good internship access.', 51);

-- ---- TIER 3: Strong Public Universities (30) ----

INSERT INTO universities (name, slug, city, state, type, acceptance_rate, avg_sat, avg_act, min_toefl, min_ielts, tuition_in_state, tuition_out_of_state, tuition_international, room_and_board, estimated_total_cost, avg_financial_aid, international_aid_available, merit_scholarships_available, need_blind_international, test_optional, total_enrollment, international_student_pct, student_faculty_ratio, popular_majors, campus_setting, website, description, us_news_rank) VALUES
('University of California Berkeley', 'uc-berkeley', 'Berkeley', 'CA', 'public', 11.64, 1460, 33, 80, 6.5, 14312, 44066, 48176, 20478, 68654, 20000, true, true, false, false, 45307, 16.2, '20:1', ARRAY['Computer Science','Engineering','Business','Biology','Economics'], 'urban', 'https://www.berkeley.edu', 'UC Berkeley is the top public university in the US. World-class STEM and business programs. International students pay out-of-state tuition but can access merit scholarships.', 15),
('University of California Los Angeles', 'ucla', 'Los Angeles', 'CA', 'public', 8.56, 1440, 33, 83, 7.0, 13401, 43003, 47009, 18324, 65333, 18000, true, true, false, false, 46430, 12.6, '18:1', ARRAY['Biology','Psychology','Economics','Political Science','Computer Science'], 'urban', 'https://www.ucla.edu', 'UCLA combines academic excellence with Southern California lifestyle. Strong sciences and arts programs. Limited but available financial support for international students.', 15),
('University of Michigan', 'umich', 'Ann Arbor', 'MI', 'public', 17.65, 1440, 33, 88, 7.0, 16736, 55334, 55334, 12592, 67926, 18000, true, true, false, false, 48090, 8.4, '15:1', ARRAY['Computer Science','Engineering','Business','Biology','Economics'], 'urban', 'https://www.umich.edu', 'UMich is one of the top public research universities. Ross School of Business and College of Engineering are world-renowned. Some merit scholarships for international students.', 21),
('University of Virginia', 'uva', 'Charlottesville', 'VA', 'public', 16.30, 1440, 33, 90, 7.0, 19814, 53666, 55914, 14016, 69930, 18000, true, true, false, false, 26043, 8.2, '15:1', ARRAY['Business','Economics','Biology','Computer Science','Engineering'], 'suburban', 'https://www.virginia.edu', 'UVA offers the Jefferson Scholars program with full funding for exceptional students including internationals. Beautiful campus founded by Thomas Jefferson.', 24),
('Georgia Institute of Technology', 'georgia-tech', 'Atlanta', 'GA', 'public', 16.95, 1460, 33, 90, 7.0, 12682, 33794, 33794, 14612, 48406, 14000, true, true, false, false, 44000, 14.3, '22:1', ARRAY['Computer Science','Engineering','Business','Biology','Industrial Engineering'], 'urban', 'https://www.gatech.edu', 'Georgia Tech is a top engineering and CS school with relatively affordable international tuition. Strong co-op program. Located in Atlanta with tech industry connections.', 33),
('University of Texas at Austin', 'ut-austin', 'Austin', 'TX', 'public', 31.82, 1380, 31, 79, 6.5, 11448, 40996, 40996, 12748, 53744, 12000, true, true, false, false, 53082, 8.9, '17:1', ARRAY['Computer Science','Engineering','Business','Biology','Economics'], 'urban', 'https://www.utexas.edu', 'UT Austin offers excellent value for international students in STEM and business. Austin is a major tech hub. Large and diverse campus with strong school spirit.', 32),
('University of Wisconsin-Madison', 'uw-madison', 'Madison', 'WI', 'public', 49.83, 1400, 31, 80, 6.5, 10796, 39427, 39427, 13252, 52679, 12000, true, true, false, false, 49066, 8.3, '17:1', ARRAY['Computer Science','Biology','Engineering','Business','Psychology'], 'urban', 'https://www.wisc.edu', 'UW-Madison is a top public research university with moderate international tuition. Strong STEM and business programs. Vibrant college town on Lake Mendota.', 35),
('University of North Carolina at Chapel Hill', 'unc-chapel-hill', 'Chapel Hill', 'NC', 'public', 16.76, 1420, 32, 100, 7.0, 8998, 37558, 37558, 13208, 50766, 14000, true, true, false, false, 31641, 6.7, '15:1', ARRAY['Biology','Business','Computer Science','Economics','Psychology'], 'suburban', 'https://www.unc.edu', 'UNC is one of the most affordable top public universities for international students. Strong business school and sciences. Beautiful campus in charming Chapel Hill.', 22),
('University of Illinois Urbana-Champaign', 'uiuc', 'Champaign', 'IL', 'public', 43.66, 1420, 32, 79, 6.5, 16004, 34316, 36646, 12680, 49326, 14000, true, true, false, false, 56607, 16.5, '20:1', ARRAY['Computer Science','Engineering','Business','Biology','Accounting'], 'urban', 'https://www.illinois.edu', 'UIUC has a top-5 CS and engineering program. Large international student community. Affordable by private university standards. Strong alumni network in tech.', 35),
('Purdue University', 'purdue', 'West Lafayette', 'IN', 'public', 53.36, 1340, 31, 80, 6.5, 9992, 28794, 28794, 11020, 39814, 10000, true, true, false, false, 51344, 17.8, '13:1', ARRAY['Engineering','Computer Science','Business','Biology','Agriculture'], 'suburban', 'https://www.purdue.edu', 'Purdue is one of the most affordable top engineering schools for international students. Has frozen tuition for years. Strong aerospace and mechanical engineering.', 43),
('Penn State University', 'penn-state', 'University Park', 'PA', 'public', 56.00, 1300, 29, 80, 6.5, 19286, 37468, 37468, 12764, 50232, 10000, true, true, false, false, 88481, 10.1, '15:1', ARRAY['Engineering','Business','Biology','Information Sciences','Kinesiology'], 'suburban', 'https://www.psu.edu', 'Penn State has one of the largest alumni networks in the world. Strong engineering and business programs. Active campus life with Big Ten athletics.', 60),
('Ohio State University', 'ohio-state', 'Columbus', 'OH', 'public', 53.05, 1330, 30, 79, 6.5, 11936, 35019, 35019, 13282, 48301, 11000, true, true, false, false, 61369, 10.5, '19:1', ARRAY['Business','Engineering','Biology','Psychology','Communication'], 'urban', 'https://www.osu.edu', 'Ohio State offers competitive merit scholarships for international students. Large campus with strong business, engineering, and medical programs. Columbus is an affordable city.', 43),
('University of Maryland', 'umd', 'College Park', 'MD', 'public', 44.10, 1400, 32, 84, 7.0, 10779, 38636, 38636, 14104, 52740, 12000, true, true, false, false, 41200, 7.1, '18:1', ARRAY['Computer Science','Engineering','Business','Biology','Economics'], 'suburban', 'https://www.umd.edu', 'UMD offers competitive programs near Washington DC. Strong CS and engineering near government and tech employers. International merit scholarships available.', 46),
('University of Florida', 'uf', 'Gainesville', 'FL', 'public', 23.08, 1400, 32, 80, 6.0, 6380, 28658, 28658, 11590, 40248, 10000, true, true, false, false, 55781, 5.9, '17:1', ARRAY['Biology','Business','Engineering','Computer Science','Psychology'], 'suburban', 'https://www.ufl.edu', 'UF is one of the best value public universities. Affordable international tuition with strong programs across the board. Warm climate and active campus.', 28),
('Arizona State University', 'asu', 'Tempe', 'AZ', 'public', 88.12, 1260, 27, 61, 6.0, 12117, 30456, 32076, 13454, 45530, 10000, true, true, false, false, 77881, 8.3, '23:1', ARRAY['Business','Engineering','Computer Science','Biology','Psychology'], 'urban', 'https://www.asu.edu', 'ASU is the most innovative university in the US per US News. Generous merit scholarships for international students. Wide range of programs and flexible online options.', 105),
('University of Iowa', 'uiowa', 'Iowa City', 'IA', 'public', 84.46, 1240, 26, 80, 6.5, 9942, 31568, 31568, 11839, 43407, 10000, true, true, false, false, 30825, 8.7, '15:1', ARRAY['Business','Engineering','Biology','Psychology','Communication'], 'urban', 'https://www.uiowa.edu', 'University of Iowa offers automatic merit scholarships for international students based on GPA. Renowned creative writing program. Affordable college town.', 83),
('University of Minnesota', 'umn', 'Minneapolis', 'MN', 'public', 75.30, 1370, 30, 79, 6.5, 15142, 34370, 34370, 12654, 47024, 14000, true, true, false, false, 54953, 9.1, '17:1', ARRAY['Engineering','Biology','Business','Computer Science','Psychology'], 'urban', 'https://www.umn.edu', 'UMN offers Global Excellence scholarships for international students. Strong engineering and health sciences. Twin Cities area provides cultural and career opportunities.', 53),
('Indiana University Bloomington', 'indiana', 'Bloomington', 'IN', 'public', 80.14, 1230, 27, 79, 6.5, 11164, 38364, 38364, 12092, 50456, 10000, true, true, false, false, 44407, 11.4, '16:1', ARRAY['Business','Biology','Computer Science','Public Health','Music'], 'suburban', 'https://www.indiana.edu', 'Indiana University Kelley School of Business is world-renowned. Automatic merit scholarships for international students. Beautiful campus and affordable cost of living.', 72),
('Rutgers University', 'rutgers', 'New Brunswick', 'NJ', 'public', 66.05, 1330, 30, 79, 7.0, 16237, 33005, 33005, 14288, 47293, 14000, true, true, false, false, 50254, 9.9, '16:1', ARRAY['Business','Engineering','Biology','Computer Science','Psychology'], 'urban', 'https://www.rutgers.edu', 'Rutgers offers merit scholarships for international students. Located near New York City. Strong business and pharmacy programs. Large diverse campus.', 40),
('University of Connecticut', 'uconn', 'Storrs', 'CT', 'public', 56.22, 1330, 30, 79, 6.5, 17226, 40434, 40434, 14946, 55380, 11000, true, true, false, false, 32257, 6.4, '16:1', ARRAY['Business','Engineering','Biology','Nursing','Psychology'], 'rural', 'https://www.uconn.edu', 'UConn offers merit scholarships for international students. Strong business and engineering programs. Beautiful New England campus between Boston and New York.', 58),
('University of Massachusetts Amherst', 'umass-amherst', 'Amherst', 'MA', 'public', 58.04, 1350, 31, 80, 6.5, 16389, 37405, 37405, 14714, 52119, 10000, true, true, false, false, 32225, 9.3, '17:1', ARRAY['Computer Science','Engineering','Business','Biology','Psychology'], 'suburban', 'https://www.umass.edu', 'UMass Amherst has a top-20 CS program. Chancellor and Dean scholarships for international students. Five College Consortium expands course options.', 67),
('University of Oregon', 'uoregon', 'Eugene', 'OR', 'public', 83.50, 1220, 26, 61, 6.0, 13251, 37380, 37380, 14616, 51996, 8000, true, true, false, false, 23202, 10.2, '17:1', ARRAY['Business','Biology','Journalism','Psychology','Computer Science'], 'urban', 'https://www.uoregon.edu', 'University of Oregon offers the International Cultural Service Program (ICSP) scholarships. Strong journalism and business programs. Beautiful Pacific Northwest setting.', 98),
('University of Colorado Boulder', 'cu-boulder', 'Boulder', 'CO', 'public', 78.48, 1280, 28, 75, 6.5, 12500, 38318, 38318, 16730, 55048, 10000, true, true, false, false, 38303, 7.5, '18:1', ARRAY['Engineering','Business','Computer Science','Biology','Psychology'], 'suburban', 'https://www.colorado.edu', 'CU Boulder offers merit scholarships for international students. Strong aerospace engineering (near NOAA and NIST). Beautiful mountain campus.', 86),
('University of Pittsburgh', 'pitt', 'Pittsburgh', 'PA', 'public', 42.07, 1370, 31, 80, 6.5, 19718, 34124, 34124, 12996, 47120, 12000, true, true, false, false, 33752, 7.4, '14:1', ARRAY['Engineering','Biology','Business','Computer Science','Nursing'], 'urban', 'https://www.pitt.edu', 'Pitt offers merit scholarships for international students. Strong health sciences near UPMC medical center. Affordable and livable city of Pittsburgh.', 62),
('Stony Brook University', 'stony-brook', 'Stony Brook', 'NY', 'public', 49.12, 1370, 30, 80, 6.5, 10356, 27576, 27576, 15824, 43400, 8000, true, true, false, false, 26814, 16.4, '19:1', ARRAY['Computer Science','Biology','Engineering','Health Sciences','Psychology'], 'suburban', 'https://www.stonybrook.edu', 'Stony Brook offers affordable tuition for international students in the SUNY system. Strong STEM programs. Located on Long Island near NYC.', 60),
('University at Buffalo', 'buffalo', 'Buffalo', 'NY', 'public', 71.66, 1260, 27, 79, 6.5, 10099, 27969, 27969, 15390, 43359, 7000, true, true, false, false, 32347, 18.8, '14:1', ARRAY['Engineering','Business','Computer Science','Biology','Pharmacy'], 'suburban', 'https://www.buffalo.edu', 'UB has a high percentage of international students and affordable SUNY tuition. Presidential scholarships available. Strong engineering and pharmacy programs.', 89),
('Temple University', 'temple', 'Philadelphia', 'PA', 'public', 79.28, 1220, 26, 79, 6.0, 17832, 31106, 31106, 13486, 44592, 8000, true, true, false, false, 34557, 6.1, '13:1', ARRAY['Business','Communication','Biology','Education','Engineering'], 'urban', 'https://www.temple.edu', 'Temple offers merit-based scholarships for international students. Located in Philadelphia with access to internships. Fox School of Business is well-known.', 89),
('University of Houston', 'houston', 'Houston', 'TX', 'public', 65.79, 1190, 25, 79, 6.5, 10872, 26520, 26520, 12018, 38538, 7000, true, true, false, false, 46324, 8.2, '22:1', ARRAY['Engineering','Business','Biology','Computer Science','Psychology'], 'urban', 'https://www.uh.edu', 'University of Houston offers affordable tuition in a major city. Academic Excellence Scholarships for international students. Strong engineering tied to energy industry.', 122),
('Florida International University', 'fiu', 'Miami', 'FL', 'public', 58.61, 1200, 25, 80, 6.5, 6168, 18566, 18566, 11998, 30564, 6000, true, true, false, false, 55009, 6.2, '25:1', ARRAY['Business','Engineering','Biology','Hospitality','Computer Science'], 'urban', 'https://www.fiu.edu', 'FIU is one of the most affordable options for international students. Large Hispanic-serving institution in Miami. Strong hospitality and business programs.', 132),
('CUNY Baruch College', 'cuny-baruch', 'New York', 'NY', 'public', 50.98, 1280, 28, 80, 7.0, 7460, 15120, 15120, 10000, 25120, 5000, true, true, false, false, 19283, 14.5, '18:1', ARRAY['Business','Accounting','Finance','Economics','Computer Science'], 'urban', 'https://www.baruch.cuny.edu', 'Baruch College offers exceptional value for business education in NYC. Zicklin School of Business is AACSB accredited. One of the most affordable options in New York.', 20);

-- ---- TIER 4: Affordable/International-Friendly (20) ----

INSERT INTO universities (name, slug, city, state, type, acceptance_rate, avg_sat, avg_act, min_toefl, min_ielts, tuition_in_state, tuition_out_of_state, tuition_international, room_and_board, estimated_total_cost, avg_financial_aid, international_aid_available, merit_scholarships_available, need_blind_international, test_optional, total_enrollment, international_student_pct, student_faculty_ratio, popular_majors, campus_setting, website, description, us_news_rank) VALUES
('University of Alabama', 'alabama', 'Tuscaloosa', 'AL', 'public', 75.18, 1220, 27, 71, 6.0, 11580, 31960, 31960, 12404, 44364, 14000, true, true, false, false, 39327, 4.5, '19:1', ARRAY['Business','Engineering','Communication','Biology','Nursing'], 'suburban', 'https://www.ua.edu', 'Alabama offers generous automatic merit scholarships for international students based on GPA and test scores, covering up to full tuition. Affordable Southern living.', 137),
('University of South Florida', 'usf', 'Tampa', 'FL', 'public', 48.88, 1260, 27, 79, 6.5, 6410, 17324, 17324, 12520, 29844, 7000, true, true, false, false, 50577, 8.3, '22:1', ARRAY['Business','Biology','Engineering','Psychology','Health Sciences'], 'urban', 'https://www.usf.edu', 'USF offers Green and Gold Director Awards for international students. Affordable tuition with strong STEM and health programs in Tampa.', 89),
('Mississippi State University', 'mississippi-state', 'Starkville', 'MS', 'public', 79.22, 1170, 24, 71, 6.0, 9468, 25260, 25260, 11570, 36830, 8000, true, true, false, false, 22649, 3.6, '19:1', ARRAY['Engineering','Business','Biology','Agriculture','Computer Science'], 'rural', 'https://www.msstate.edu', 'Mississippi State offers competitive tuition waivers for international students. Strong engineering and agriculture programs. Very affordable cost of living.', 176),
('Western Kentucky University', 'wku', 'Bowling Green', 'KY', 'public', 96.10, 1120, 22, 71, 6.0, 10902, 27284, 27284, 10116, 37400, 8000, true, true, false, false, 15291, 5.5, '18:1', ARRAY['Business','Education','Engineering','Nursing','Biology'], 'suburban', 'https://www.wku.edu', 'WKU offers the International Reach Award reducing tuition to near in-state rates. Welcoming international community. Affordable small-city living.', 293),
('Murray State University', 'murray-state', 'Murray', 'KY', 'public', 84.18, 1100, 22, 71, 6.0, 9576, 14004, 14004, 9700, 23704, 7000, true, true, false, false, 9375, 7.2, '15:1', ARRAY['Business','Education','Agriculture','Engineering Technology','Biology'], 'rural', 'https://www.murraystate.edu', 'Murray State offers some of the lowest tuition rates for international students. Regional tuition incentives and scholarships available. Safe campus.', 40),
('Oklahoma State University', 'oklahoma-state', 'Stillwater', 'OK', 'public', 71.91, 1190, 25, 61, 6.0, 9018, 24468, 24468, 10464, 34932, 8000, true, true, false, false, 24769, 7.8, '20:1', ARRAY['Engineering','Business','Agriculture','Biology','Computer Science'], 'suburban', 'https://www.okstate.edu', 'Oklahoma State offers competitive international tuition waivers and merit scholarships. Strong engineering and agriculture. Very affordable Stillwater community.', 187),
('Kansas State University', 'kansas-state', 'Manhattan', 'KS', 'public', 94.44, 1170, 24, 79, 6.5, 10862, 27034, 27034, 11280, 38314, 7000, true, true, false, false, 20327, 7.5, '17:1', ARRAY['Engineering','Business','Agriculture','Architecture','Biology'], 'suburban', 'https://www.k-state.edu', 'K-State offers tuition waivers that bring international tuition close to in-state rates. Strong engineering and agriculture programs. Friendly college town.', 176),
('Boise State University', 'boise-state', 'Boise', 'ID', 'public', 83.52, 1130, 23, 68, 6.0, 8060, 25060, 25060, 9414, 34474, 6000, true, true, false, false, 28007, 3.2, '18:1', ARRAY['Business','Engineering','Health Sciences','Education','Biology'], 'urban', 'https://www.boisestate.edu', 'Boise State offers affordable tuition with merit scholarships for international students. Growing tech hub in Boise. Strong engineering and computer science.', 293),
('University of Texas at Arlington', 'ut-arlington', 'Arlington', 'TX', 'public', 82.50, 1140, 23, 71, 6.0, 10784, 23200, 23200, 10060, 33260, 5000, true, true, false, false, 42496, 10.5, '25:1', ARRAY['Engineering','Business','Nursing','Biology','Computer Science'], 'urban', 'https://www.uta.edu', 'UT Arlington offers affordable tuition in the Dallas-Fort Worth metroplex. Large international student population. Strong engineering and nursing programs.', 210),
('Texas Tech University', 'texas-tech', 'Lubbock', 'TX', 'public', 72.13, 1160, 24, 79, 6.5, 8780, 21480, 21480, 10236, 31716, 6000, true, true, false, false, 40666, 6.4, '20:1', ARRAY['Engineering','Business','Biology','Agriculture','Health Sciences'], 'urban', 'https://www.ttu.edu', 'Texas Tech offers competitive international tuition rates and merit scholarships. Strong engineering and health sciences. Affordable West Texas living.', 176),
('Marshall University', 'marshall', 'Huntington', 'WV', 'public', 88.05, 1090, 22, 61, 6.0, 8878, 19446, 19446, 10892, 30338, 5000, true, true, false, false, 12062, 3.8, '17:1', ARRAY['Business','Engineering','Biology','Health Sciences','Education'], 'urban', 'https://www.marshall.edu', 'Marshall offers very affordable tuition for international students. INTO Marshall pathway program helps with English preparation. Supportive environment.', 293),
('University of Alabama at Birmingham', 'uab', 'Birmingham', 'AL', 'public', 85.14, 1190, 25, 77, 6.5, 9200, 21330, 21330, 11230, 32560, 7000, true, true, false, false, 22563, 4.3, '17:1', ARRAY['Nursing','Biology','Business','Engineering','Public Health'], 'urban', 'https://www.uab.edu', 'UAB offers the Blazer International Merit Award covering significant tuition. Strong health sciences and nursing near major medical center. Research-intensive.', 148),
('University of Tulsa', 'tulsa', 'Tulsa', 'OK', 'private_nonprofit', 70.52, 1260, 28, 80, 6.0, 44726, 44726, 44726, 12874, 57600, 25000, true, true, false, true, 3472, 20.5, '11:1', ARRAY['Engineering','Business','Computer Science','Biology','Law'], 'urban', 'https://www.utulsa.edu', 'University of Tulsa offers generous merit scholarships covering up to full tuition for international students. Small classes with personal attention. Strong engineering.', 137),
('St. Cloud State University', 'st-cloud', 'St. Cloud', 'MN', 'public', 91.00, 1050, 20, 61, 5.5, 8698, 16454, 16454, 9500, 25954, 4000, true, true, false, false, 10649, 11.2, '20:1', ARRAY['Business','Education','Engineering Technology','Biology','Communication'], 'suburban', 'https://www.stcloudstate.edu', 'St. Cloud State offers very affordable tuition for international students. Friendly campus with strong support services. Cultural diversity programs.', 96),
('Southeast Missouri State University', 'semo', 'Cape Girardeau', 'MO', 'public', 89.75, 1080, 21, 61, 5.5, 7965, 14265, 14265, 10244, 24509, 4000, true, true, false, false, 10677, 3.5, '18:1', ARRAY['Business','Education','Engineering Technology','Biology','Health Sciences'], 'suburban', 'https://www.semo.edu', 'SEMO offers some of the lowest tuition rates for international students. International tuition reduced to near domestic rates. Supportive small campus.', 96),
('Northern Illinois University', 'niu', 'DeKalb', 'IL', 'public', 73.79, 1100, 22, 68, 6.0, 14634, 14634, 14634, 12096, 26730, 5000, true, true, false, false, 15553, 3.1, '14:1', ARRAY['Business','Engineering','Education','Biology','Computer Science'], 'suburban', 'https://www.niu.edu', 'NIU charges international students the same rate as domestic students. Affordable option near Chicago. Strong business and engineering programs.', 263),
('Wichita State University', 'wichita-state', 'Wichita', 'KS', 'public', 95.50, 1110, 22, 68, 6.0, 8148, 17748, 17748, 10300, 28048, 4000, true, true, false, false, 15438, 8.6, '19:1', ARRAY['Engineering','Business','Health Sciences','Aviation','Biology'], 'urban', 'https://www.wichita.edu', 'Wichita State offers affordable tuition with aviation and engineering programs connected to the aerospace industry. Merit scholarships for international students.', 293),
('Youngstown State University', 'youngstown-state', 'Youngstown', 'OH', 'public', 74.11, 1060, 21, 61, 5.5, 9431, 9431, 9431, 10400, 19831, 4000, true, true, false, false, 10910, 2.5, '16:1', ARRAY['Engineering','Business','Education','Nursing','Biology'], 'urban', 'https://www.ysu.edu', 'YSU charges international students the same rate as in-state students, making it one of the most affordable options. Strong engineering and STEM programs.', 293),
('Central Michigan University', 'cmu-michigan', 'Mount Pleasant', 'MI', 'public', 72.48, 1080, 22, 61, 5.5, 13110, 13110, 13110, 10628, 23738, 5000, true, true, false, false, 13498, 2.9, '16:1', ARRAY['Business','Education','Health Sciences','Biology','Psychology'], 'suburban', 'https://www.cmich.edu', 'Central Michigan offers international students the same tuition as domestic students. Affordable small-town living. Strong education and health programs.', 263),
('Wright State University', 'wright-state', 'Dayton', 'OH', 'public', 96.77, 1080, 22, 61, 6.0, 9540, 19146, 19146, 11614, 30760, 5000, true, true, false, false, 10733, 4.8, '14:1', ARRAY['Engineering','Business','Biology','Nursing','Computer Science'], 'suburban', 'https://www.wright.edu', 'Wright State offers scholarships reducing international tuition significantly. Named after the Wright Brothers with strong aerospace connections. Near Wright-Patterson Air Force Base.', 293);

-- ---- TIER 5: Community Colleges (15) ----

INSERT INTO universities (name, slug, city, state, type, acceptance_rate, avg_sat, avg_act, min_toefl, min_ielts, tuition_in_state, tuition_out_of_state, tuition_international, room_and_board, estimated_total_cost, avg_financial_aid, international_aid_available, merit_scholarships_available, need_blind_international, test_optional, total_enrollment, international_student_pct, student_faculty_ratio, popular_majors, campus_setting, website, description, us_news_rank) VALUES
('Santa Monica College', 'santa-monica-college', 'Santa Monica', 'CA', 'public', 100.00, NULL, NULL, 45, 5.0, 1104, 8904, 11016, 14000, 25016, 2000, false, true, false, true, 28000, 11.5, '30:1', ARRAY['Business','Computer Science','Liberal Arts','Film','Nursing'], 'urban', 'https://www.smc.edu', 'Santa Monica College is the number one transfer school to UCLA. Affordable pathway to UC and CSU universities. Large international student community near the beach.', NULL),
('De Anza College', 'de-anza', 'Cupertino', 'CA', 'public', 100.00, NULL, NULL, 45, 5.0, 1104, 5664, 6864, 14000, 20864, 1500, false, true, false, true, 20000, 13.2, '30:1', ARRAY['Computer Science','Business','Engineering','Biology','Liberal Arts'], 'suburban', 'https://www.deanza.edu', 'De Anza College is located in Silicon Valley and is a top transfer school to UC Berkeley and UCLA. Strong STEM programs and active international student services.', NULL),
('Diablo Valley College', 'diablo-valley', 'Pleasant Hill', 'CA', 'public', 100.00, NULL, NULL, 45, 5.0, 1104, 5664, 6864, 13000, 19864, 1500, false, true, false, true, 20000, 7.1, '28:1', ARRAY['Business','Liberal Arts','Biology','Engineering','Computer Science'], 'suburban', 'https://www.dvc.edu', 'Diablo Valley College is a top transfer feeder to UC Berkeley. Affordable tuition with strong transfer counseling. Diverse student body in East Bay.', NULL),
('Bergen Community College', 'bergen-cc', 'Paramus', 'NJ', 'public', 100.00, NULL, NULL, 55, 5.5, 5040, 10080, 10488, 12000, 22488, 1000, false, true, false, true, 13000, 5.2, '22:1', ARRAY['Business','Liberal Arts','Health Sciences','Computer Science','Engineering'], 'suburban', 'https://www.bergen.edu', 'Bergen CC offers affordable tuition near New York City with strong transfer pathways to Rutgers, NJIT, and other NJ universities. Supportive international student office.', NULL),
('Montgomery College', 'montgomery-college', 'Rockville', 'MD', 'public', 100.00, NULL, NULL, 55, 5.5, 5088, 11484, 14160, 13000, 27160, 1000, false, true, false, true, 50000, 7.8, '20:1', ARRAY['Business','Computer Science','Health Sciences','Liberal Arts','Engineering'], 'suburban', 'https://www.montgomerycollege.edu', 'Montgomery College near Washington DC offers transfer pathways to University of Maryland and other state schools. Large international community. Very affordable.', NULL),
('Northern Virginia Community College', 'nova-cc', 'Annandale', 'VA', 'public', 100.00, NULL, NULL, 55, 5.5, 5715, 11445, 11445, 13000, 24445, 1000, false, true, false, true, 67000, 9.5, '21:1', ARRAY['Business','Engineering','Computer Science','Liberal Arts','Health Sciences'], 'suburban', 'https://www.nvcc.edu', 'NOVA is the largest community college in Virginia with guaranteed transfer to George Mason and UVA. Strong engineering pathway. Large international student population.', NULL),
('Hillsborough Community College', 'hillsborough-cc', 'Tampa', 'FL', 'public', 100.00, NULL, NULL, 45, 5.0, 2534, 9302, 9302, 12000, 21302, 1000, false, true, false, true, 43000, 4.5, '25:1', ARRAY['Business','Health Sciences','Liberal Arts','Computer Science','Education'], 'urban', 'https://www.hccfl.edu', 'Hillsborough CC offers affordable Florida tuition with transfer pathways to USF and UF. Warm climate and growing Tampa job market.', NULL),
('Lone Star College', 'lone-star', 'Houston', 'TX', 'public', 100.00, NULL, NULL, 55, 5.0, 2088, 4728, 5016, 11000, 16016, 800, false, true, false, true, 80000, 5.8, '22:1', ARRAY['Business','Health Sciences','Engineering','Computer Science','Liberal Arts'], 'urban', 'https://www.lonestar.edu', 'Lone Star College is one of the most affordable options in the Houston area. Transfer pathways to University of Houston and Texas A&M. Large and diverse campus system.', NULL),
('Dallas College', 'dallas-college', 'Dallas', 'TX', 'public', 100.00, NULL, NULL, 55, 5.0, 1770, 3330, 5790, 11000, 16790, 800, false, true, false, true, 80000, 6.3, '24:1', ARRAY['Business','Computer Science','Health Sciences','Liberal Arts','Engineering'], 'urban', 'https://www.dallascollege.edu', 'Dallas College (formerly DCCCD) offers extremely affordable tuition with transfer agreements to UT Dallas, UNT, and other Texas universities. Seven campuses across Dallas.', NULL),
('Maricopa Community Colleges', 'maricopa-cc', 'Tempe', 'AZ', 'public', 100.00, NULL, NULL, 45, 5.0, 2070, 7854, 7854, 11000, 18854, 800, false, true, false, true, 150000, 4.1, '22:1', ARRAY['Business','Liberal Arts','Health Sciences','Computer Science','Engineering'], 'urban', 'https://www.maricopa.edu', 'Maricopa is one of the largest community college systems with guaranteed transfer to ASU. MCCCD International Education program supports students. Very affordable.', NULL),
('Seattle Central College', 'seattle-central', 'Seattle', 'WA', 'public', 100.00, NULL, NULL, 52, 5.0, 4000, 4000, 10677, 13000, 23677, 1000, false, true, false, true, 14000, 15.3, '21:1', ARRAY['Business','Computer Science','Liberal Arts','Culinary Arts','Health Sciences'], 'urban', 'https://www.seattlecentral.edu', 'Seattle Central is one of the top community colleges for international students. Transfer pathways to UW Seattle. Located in vibrant Capitol Hill neighborhood.', NULL),
('Bellevue College', 'bellevue-college', 'Bellevue', 'WA', 'public', 100.00, NULL, NULL, 52, 5.0, 3855, 3855, 9831, 13000, 22831, 800, false, true, false, true, 25000, 10.7, '22:1', ARRAY['Computer Science','Business','Health Sciences','Liberal Arts','Engineering'], 'suburban', 'https://www.bellevuecollege.edu', 'Bellevue College is near Microsoft and Amazon headquarters. Strong CS and business programs with transfer pathways to UW. Large international student community.', NULL),
('Pasadena City College', 'pasadena-cc', 'Pasadena', 'CA', 'public', 100.00, NULL, NULL, 45, 5.0, 1104, 8136, 8136, 13000, 21136, 1500, false, true, false, true, 24000, 8.9, '28:1', ARRAY['Business','Liberal Arts','Engineering','Computer Science','Biology'], 'urban', 'https://www.pasadena.edu', 'Pasadena City College is a top California transfer school. Near Caltech and JPL. Strong STEM programs with pathways to UCLA, USC, and UC schools.', NULL),
('College of San Mateo', 'san-mateo', 'San Mateo', 'CA', 'public', 100.00, NULL, NULL, 45, 5.0, 1104, 5664, 6864, 14000, 20864, 1200, false, true, false, true, 8000, 8.5, '25:1', ARRAY['Business','Computer Science','Liberal Arts','Engineering','Biology'], 'suburban', 'https://www.collegeofsanmateo.edu', 'College of San Mateo is located between San Francisco and Silicon Valley. Strong transfer rates to UC Berkeley and other UCs. Small classes and personal attention.', NULL),
('Miami Dade College', 'miami-dade', 'Miami', 'FL', 'public', 100.00, NULL, NULL, 45, 5.0, 2759, 9655, 9655, 12000, 21655, 1500, false, true, false, true, 120000, 7.3, '26:1', ARRAY['Business','Health Sciences','Liberal Arts','Engineering','Computer Science'], 'urban', 'https://www.mdc.edu', 'Miami Dade College is the largest institution of higher education in the US. Very diverse student body. Affordable with transfer pathways to FIU and UF. Multiple campuses in Miami.', NULL);


-- ============================================================
-- 3. SEED DATA — SCHOLARSHIPS
-- ============================================================

-- ---- FULL-RIDE SCHOLARSHIPS (10) ----

INSERT INTO scholarships (name, slug, provider, type, amount_min, amount_max, covers_tuition, covers_living, renewable, duration_years, eligible_countries, eligible_majors, min_gpa, min_toefl, min_ielts, education_level, income_requirement, first_gen_only, deadline, application_url, description, requirements, university_id) VALUES
('Mastercard Foundation Scholars Program', 'mastercard-foundation-scholars', 'Mastercard Foundation', 'full_ride', 60000, 80000, true, true, true, 4, ARRAY['All African countries'], NULL, 3.00, 80, 6.5, ARRAY['undergraduate','graduate'], 'Demonstrated financial need required', false, 'Varies by partner university', 'https://mastercardfdn.org/all/scholars/', 'The Mastercard Foundation Scholars Program provides comprehensive financial support to academically talented yet economically disadvantaged students from Africa. Covers tuition, accommodation, books, transportation, and living expenses. Available at partner universities including UC Berkeley, Duke, Michigan, and others.', 'Must be from an African country. Demonstrated financial need. Strong academic record. Commitment to giving back to community. Leadership potential.', NULL),
('Stamps Scholarship', 'stamps-scholarship', 'Stamps Family Charitable Foundation', 'full_ride', 50000, 80000, true, true, true, 4, NULL, NULL, 3.80, NULL, NULL, ARRAY['undergraduate'], NULL, false, 'Varies by partner university', 'https://www.stampsfoundation.org/', 'The Stamps Scholarship covers the full cost of attendance at 40+ partner universities including Georgia Tech, Purdue, Michigan, UVA, and Miami. Includes enrichment fund of $12,000-$16,000 for study abroad, research, and internships.', 'Nominated by partner university during admissions. Top academic achievement. Leadership and community service. Enrichment funds for unique experiences.', NULL),
('QuestBridge National College Match', 'questbridge-match', 'QuestBridge', 'full_ride', 60000, 85000, true, true, true, 4, NULL, NULL, 3.50, NULL, NULL, ARRAY['undergraduate'], 'Family income typically under $65,000', false, 'September (application), October (ranking)', 'https://www.questbridge.org/high-school-students/national-college-match', 'QuestBridge matches high-achieving, low-income students with full four-year scholarships at 50+ partner colleges including all Ivies, Stanford, MIT, and more. Covers tuition, room, board, books, and travel.', 'US citizen, permanent resident, or undocumented student. Household income typically under $65,000. Outstanding academic record despite financial hardship.', NULL),
('Gates Scholarship', 'gates-scholarship', 'Bill & Melinda Gates Foundation', 'full_ride', 50000, 80000, true, true, true, 4, NULL, NULL, 3.30, NULL, NULL, ARRAY['undergraduate'], 'Pell-eligible (US citizens/residents only)', false, 'September 15', 'https://www.thegatesscholarship.org/', 'The Gates Scholarship covers the full cost of attendance not already covered by financial aid and EFC. For Pell-eligible minority students. Note: Limited to US citizens/permanent residents but included for eligible international students with permanent residency.', 'Must be Pell-eligible. African American, American Indian, Asian/Pacific Islander, or Hispanic American. Minimum 3.3 GPA. US citizen or permanent resident.', NULL),
('Davis-UWC Scholars Program', 'davis-uwc-scholars', 'Davis United World College Scholars Program', 'full_ride', 40000, 75000, true, true, true, 4, NULL, NULL, 3.00, 80, 6.5, ARRAY['undergraduate'], 'Need-based', false, 'Varies by partner university', 'https://www.davisuwcscholars.org/', 'The Davis-UWC Scholars Program provides scholarships to graduates of United World Colleges attending one of 100+ partner universities in the US. Awards range from partial to full funding based on need.', 'Must be a graduate of a United World College (UWC). Admitted to a Davis-UWC partner university. Financial need demonstrated through CSS Profile or institutional application.', NULL),
('Coca-Cola Scholars Program', 'coca-cola-scholars', 'Coca-Cola Scholars Foundation', 'full_ride', 20000, 20000, false, false, true, 4, NULL, NULL, 3.00, NULL, NULL, ARRAY['undergraduate'], NULL, false, 'October 31', 'https://www.coca-colascholarsfoundation.org/', 'The Coca-Cola Scholars Program awards $20,000 scholarships to 150 high school seniors annually. Focuses on leadership, service, and academics. One of the most prestigious merit scholarships in the US.', 'Current high school senior. US citizen, permanent resident, or DACA. Minimum 3.0 GPA. Strong leadership and community service record.', NULL),
('Aga Khan Foundation International Scholarship', 'aga-khan-scholarship', 'Aga Khan Foundation', 'full_ride', 30000, 70000, true, true, true, 2, ARRAY['Bangladesh','India','Pakistan','Afghanistan','Tajikistan','Kyrgyzstan','Syria','Egypt','Kenya','Tanzania','Uganda','Madagascar','Mozambique'], NULL, 3.00, 80, 6.5, ARRAY['graduate'], 'Demonstrated financial need', false, 'March 31', 'https://www.akdn.org/our-agencies/aga-khan-foundation/international-scholarship-programme', 'The Aga Khan Foundation provides scholarships for postgraduate studies to outstanding students from developing countries who have no other means of financing. 50% grant and 50% loan. Covers tuition and living expenses.', 'From eligible developing country. Admitted to a reputable university. No other means of financing studies. Commitment to return to home country or developing world.', NULL),
('YSEALI Academic Fellowship', 'yseali-fellowship', 'US Department of State', 'full_ride', 25000, 40000, true, true, false, 1, ARRAY['Brunei','Cambodia','Indonesia','Laos','Malaysia','Myanmar','Philippines','Singapore','Thailand','Vietnam','Timor-Leste'], NULL, 3.00, 79, 6.5, ARRAY['undergraduate'], NULL, false, 'Varies (typically spring)', 'https://asean.usmission.gov/yseali/', 'YSEALI Academic Fellowships bring undergraduate students from ASEAN nations to US universities for one semester of academic study. Fully funded including travel, tuition, housing, and living expenses.', 'Citizen of an ASEAN country. Age 18-25. Currently enrolled in undergraduate program. Strong English proficiency. Interest in civic engagement, environment, or economic development.', NULL),
('EducationUSA Opportunity Funds', 'educationusa-opportunity', 'US Department of State', 'full_ride', 5000, 80000, true, true, false, 4, NULL, NULL, 3.50, 80, 6.5, ARRAY['undergraduate'], 'Demonstrated significant financial need', false, 'Varies by EducationUSA center', 'https://educationusa.state.gov/scholarships', 'EducationUSA Opportunity Funds help highly qualified students who are likely to be admitted to US universities with full financial aid but cannot afford the upfront costs of testing, applications, and travel. Works as a bridge to full university aid.', 'Must be identified by a local EducationUSA advising center. High academic achievement. Significant financial need. Strong potential for admission with full financial aid.', NULL),
('MasterCard Foundation Scholars at UC Berkeley', 'mastercard-ucb', 'Mastercard Foundation & UC Berkeley', 'full_ride', 70000, 75000, true, true, true, 4, ARRAY['All African countries'], NULL, 3.50, 80, 6.5, ARRAY['undergraduate','graduate'], 'Demonstrated financial need', false, 'November 30 (UC Berkeley deadline)', 'https://mastercardfdn.org/all/scholars/becoming-a-scholar/university-of-california-berkeley/', 'Full scholarship for African students at UC Berkeley covering tuition, housing, meals, books, health insurance, and travel. Includes mentoring, leadership development, and career support. One of the most comprehensive scholarships for African students.', 'Must be from sub-Saharan Africa. Admitted to UC Berkeley. Demonstrated financial need and academic excellence. Commitment to returning to Africa to contribute to community development.', (SELECT id FROM universities WHERE slug = 'uc-berkeley'));

-- ---- UNIVERSITY-SPECIFIC INTERNATIONAL MERIT SCHOLARSHIPS (15) ----

INSERT INTO scholarships (name, slug, provider, type, amount_min, amount_max, covers_tuition, covers_living, renewable, duration_years, eligible_countries, eligible_majors, min_gpa, min_toefl, min_ielts, education_level, income_requirement, first_gen_only, deadline, application_url, description, requirements, university_id) VALUES
('University of Alabama International Merit Scholarships', 'alabama-international-merit', 'University of Alabama', 'merit', 12000, 28000, true, false, true, 4, NULL, NULL, 3.00, 71, 6.0, ARRAY['undergraduate'], NULL, false, 'December 15 (priority)', 'https://scholarships.ua.edu/international/', 'Alabama offers automatic merit scholarships for international freshmen based on GPA. Awards range from $12,000 to full tuition ($28,000+). One of the most generous automatic scholarship programs for international students.', 'International freshman applicant. Based on unweighted GPA on 4.0 scale. Automatic consideration with admission application. Renewable with maintained GPA.', (SELECT id FROM universities WHERE slug = 'alabama')),
('Iowa International Merit Scholarships', 'iowa-international-merit', 'University of Iowa', 'merit', 5000, 15000, false, false, true, 4, NULL, NULL, 3.00, 80, 6.5, ARRAY['undergraduate'], NULL, false, 'February 1 (priority)', 'https://admissions.uiowa.edu/finances/scholarships-international-students', 'University of Iowa offers automatic merit scholarships for international students ranging from $5,000 to $15,000 annually. Combined with competitive tuition, Iowa is an affordable option for international students.', 'International freshman applicant. Based on academic record. Automatic consideration. Renewable with good academic standing.', (SELECT id FROM universities WHERE slug = 'uiowa')),
('USF Green and Gold Director Award', 'usf-green-gold', 'University of South Florida', 'merit', 4000, 12000, false, false, true, 4, NULL, NULL, 3.00, 79, 6.5, ARRAY['undergraduate'], NULL, false, 'January 15 (priority)', 'https://www.usf.edu/admissions/international/scholarships/', 'USF offers Green and Gold Director Awards for international freshmen based on academic achievement. Awards range from $4,000 to $12,000 per year, making USF very affordable for international students.', 'International freshman applicant. Strong academic record. Automatic consideration with admission. Renewable with maintained GPA.', (SELECT id FROM universities WHERE slug = 'usf')),
('ASU New American University Scholarship', 'asu-new-american', 'Arizona State University', 'merit', 5000, 16000, false, false, true, 4, NULL, NULL, 3.00, 61, 6.0, ARRAY['undergraduate'], NULL, false, 'Rolling', 'https://students.asu.edu/international/scholarships', 'ASU offers the New American University Scholarship for international students ranging from $5,000 to $16,000 per year. One of the most accessible merit scholarship programs for international students.', 'International freshman applicant. Based on GPA and test scores. Automatic consideration. Renewable with good academic standing.', (SELECT id FROM universities WHERE slug = 'asu')),
('BU Trustee Scholarship', 'bu-trustee', 'Boston University', 'merit', 25000, 58000, true, false, true, 4, NULL, NULL, 3.80, 90, 7.0, ARRAY['undergraduate'], NULL, false, 'December 1', 'https://www.bu.edu/admissions/tuition-aid/scholarships-financial-aid/first-year-merit/', 'Boston University Trustee Scholarships cover full tuition for the most exceptional applicants including international students. Presidential Scholarships cover 75% and Dean Scholarships cover 50%.', 'Must apply by Early Decision or Regular Decision deadline. Top academic achievement. Exceptional extracurricular involvement. No separate application required.', (SELECT id FROM universities WHERE slug = 'boston-university')),
('Brandeis Wien International Scholarship', 'brandeis-wien', 'Brandeis University', 'merit', 25000, 60000, true, true, true, 4, NULL, NULL, 3.50, 90, 7.0, ARRAY['undergraduate'], 'Need-based component', false, 'November 1 (ED) / January 2 (RD)', 'https://www.brandeis.edu/financial-aid/apply/international-students.html', 'The Wien International Scholarship at Brandeis covers full tuition and possibly room and board for exceptional international students. One of the most generous scholarships at any mid-tier university.', 'International student. Outstanding academic record. Demonstrated financial need. Strong personal qualities and leadership.', (SELECT id FROM universities WHERE slug = 'brandeis')),
('Emory University Scholarship Program', 'emory-merit', 'Emory University', 'merit', 16000, 32000, false, false, true, 4, NULL, NULL, 3.50, 100, 7.0, ARRAY['undergraduate'], NULL, false, 'November 15 (ED) / January 1 (RD)', 'https://apply.emory.edu/afford/scholarships-and-grants.html', 'Emory offers Dean and Emory Scholars awards to the most exceptional applicants including international students. Awards range from half to full tuition. Separate scholars application required.', 'Apply by regular admission deadline. Some require separate scholarship essay. Top academic achievement and extracurriculars.', (SELECT id FROM universities WHERE slug = 'emory')),
('Case Western Reserve University Merit Awards', 'case-western-merit', 'Case Western Reserve University', 'merit', 15000, 54000, true, false, true, 4, NULL, NULL, 3.50, 90, 7.0, ARRAY['undergraduate'], NULL, false, 'November 1 (EA) / January 15 (RD)', 'https://case.edu/admission/financial-aid/scholarships', 'Case Western offers merit scholarships up to full tuition for international students. Awards include the Distinguished Scholar, University Scholar, and Faculty Scholar awards.', 'International applicant with strong academic credentials. Automatic consideration with admission application. Some awards require separate application.', (SELECT id FROM universities WHERE slug = 'case-western')),
('American University Emerging Global Leader Scholarship', 'au-emerging-global-leader', 'American University', 'full_ride', 60000, 72000, true, true, true, 4, NULL, NULL, 3.80, 80, 6.5, ARRAY['undergraduate'], 'Demonstrated financial need', false, 'December 1', 'https://www.american.edu/admissions/international/emerging-global-leader.cfm', 'American University awards one full-ride scholarship per year to an international student who demonstrates leadership, academic excellence, and a commitment to positive civic and social change.', 'International student. Outstanding academic record (top 10%). Demonstrated financial need. Strong leadership and community engagement. Plan to return home to improve community.', (SELECT id FROM universities WHERE slug = 'american-university')),
('Tulsa International Student Merit Scholarships', 'tulsa-international-merit', 'University of Tulsa', 'merit', 10000, 44000, true, false, true, 4, NULL, NULL, 3.00, 80, 6.0, ARRAY['undergraduate'], NULL, false, 'January 15', 'https://admission.utulsa.edu/tuition-and-aid/scholarships/international-students/', 'University of Tulsa offers merit scholarships covering up to full tuition for international students. One of the most generous private university scholarship programs for internationals.', 'International applicant. Based on academic achievement and test scores. Automatic consideration with admission. Renewable with maintained GPA.', (SELECT id FROM universities WHERE slug = 'tulsa')),
('Minnesota Global Excellence Scholarship', 'umn-global-excellence', 'University of Minnesota', 'merit', 10000, 25000, false, false, true, 4, NULL, NULL, 3.50, 79, 6.5, ARRAY['undergraduate'], NULL, false, 'December 1', 'https://admissions.tc.umn.edu/costsaid/scholarships_international.html', 'UMN offers Global Excellence Scholarships of $10,000-$25,000 annually for outstanding international freshmen. Combines with affordable tuition to make UMN accessible.', 'International freshman applicant. Strong academic record. Automatic consideration with admission application. Renewable with good academic standing.', (SELECT id FROM universities WHERE slug = 'umn')),
('Purdue Merit Scholarships for International Students', 'purdue-international-merit', 'Purdue University', 'merit', 4000, 16000, false, false, true, 4, NULL, NULL, 3.50, 80, 6.5, ARRAY['undergraduate'], NULL, false, 'January 1', 'https://www.admissions.purdue.edu/costsandfinaid/internationalawards.php', 'Purdue offers merit-based scholarships for international students in engineering and sciences. Awards range from $4,000 to $16,000. Combined with frozen tuition, Purdue is very affordable.', 'International applicant to Purdue. Based on academic excellence. Automatic consideration with admission. Specific college may have additional awards.', (SELECT id FROM universities WHERE slug = 'purdue')),
('Ohio State International Scholarships', 'ohio-state-international', 'Ohio State University', 'merit', 5000, 15000, false, false, true, 4, NULL, NULL, 3.30, 79, 6.5, ARRAY['undergraduate'], NULL, false, 'November 1 (priority)', 'https://sfa.osu.edu/incoming-freshmen/international-students', 'Ohio State offers the Provost International Scholarship and other merit awards for international freshmen. Awards range from $5,000 to $15,000 per year.', 'International freshman applicant. Based on academic record and achievements. Automatic consideration with admission application.', (SELECT id FROM universities WHERE slug = 'ohio-state')),
('Indiana University Dean International Award', 'iu-dean-international', 'Indiana University Bloomington', 'merit', 6000, 15000, false, false, true, 4, NULL, NULL, 3.00, 79, 6.5, ARRAY['undergraduate'], NULL, false, 'February 1', 'https://ois.iu.edu/admissions/scholarships/index.html', 'IU Bloomington offers automatic merit scholarships for international students based on GPA. Dean International Award ranges from $6,000 to $15,000 annually.', 'International freshman applicant. Automatic based on GPA. Renewable with maintained GPA.', (SELECT id FROM universities WHERE slug = 'indiana')),
('NYU Abu Dhabi Full Scholarship', 'nyuad-full-scholarship', 'New York University Abu Dhabi', 'full_ride', 79000, 83000, true, true, true, 4, NULL, NULL, 3.50, 100, 7.5, ARRAY['undergraduate'], 'Need-based', false, 'January 5', 'https://nyuad.nyu.edu/en/admissions/financial-aid.html', 'NYU Abu Dhabi offers full-ride scholarships covering tuition, housing, dining, textbook allowance, travel, and health insurance. One of the most generous full-ride programs for international students globally.', 'Apply to NYU Abu Dhabi through Common App. Financial aid is 100% need-based and meets full demonstrated need for all admitted students regardless of nationality.', (SELECT id FROM universities WHERE slug = 'nyu'));
